teaching_pool_project/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

app_name = 'api'

urlpatterns = {
    url(r'v1/persons/', Persons.as_view(), name="persons"),
    url(r'v1/person/?(?P<pk>[^/]+)/$', PersonDetail.as_view(), name="person_details"),
    url(r'v1/courses/', Courses.as_view(), name="courses"),
    url(r'v1/course/(?P<pk>\d*)/$', CourseDetail.as_view(), name="course_details_by_id"),
    url(r'v1/course/(?P<year>.*)/(?P<term>.*)/(?P<code>.*)/$', CourseDetailByYearTermCode.as_view(), name="course_details_by_year_term_code"),
    url(r'v1/teachings/$', Teachings.as_view(), name="teachings"),
    url(r'v1/teachings/(?P<sciper>\d*)/$', TeachingsBySciper.as_view(), name="teachings_by_sciper")
}

urlpatterns = format_suffix_patterns(urlpatterns)

teaching_pool_project/teaching_pool_project/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_tequila.urls import urlpatterns as django_tequila_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('web.urls')),
    path('api/', include('api.urls')),
]
urlpatterns += django_tequila_urlpatterns

if settings.DEBUG:
    print("importing debug_toolbar")
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

teaching_pool_project/web/urls.py
from django.urls import path, re_path

from web.views import views, timereporting_views, mailer_views, application_views

app_name = 'web'

urlpatterns = [
    path('', views.index, name="index"),
    re_path(r'courses/(?P<year>\d{4}-\d{4})$', views.courses_full_list, name="courses_full_list"),
    re_path(r'courses/(?P<year>\d{4}-\d{4})/my', views.courses_list_year_teacher, name="courses_list_year_teacher"),
    re_path(r'TAs/request/(?P<course_id>\d*$)', views.request_for_TA, name="request_for_TA"),
    re_path(r'TAs/accept/(?P<course_id>\d*$)', views.accept_theoretical_number_of_tas, name="accept_theoretical_number_of_tas"),
    path('requests/TAs/', views.get_TAs_requests_to_validate, name="get_TAs_requests_to_validate"),
    re_path(r'requests/TAs/review/(?P<request_id>\d*$)', views.validate_request_for_TA, name="validate_request_for_TA"),
    re_path(r'requests/TAs/view/(?P<request_id>\d*$)', views.view_request_for_TA, name="view_request_for_TA"),
    path('requests/TAs/my/', views.requests_for_tas_teacher, name="requests_for_tas_teacher"),
    re_path(r'requests/TAs/my/(?P<status>.*$)', views.requests_for_tas_teacher_status, name="requests_for_tas_teacher_status"),
    re_path(r'requests/TAs/reports/full_list/(?P<year>\d{4}-\d{4})/(?P<term>.*)$', views.courses_report, name="courses_report"),
    re_path(r'requests/TAs/reports/full_list/(?P<year>\d{4}-\d{4})/(?P<term>.*)/download/$', views.download_course_report, name="download_course_report"),
    re_path('requests/TAs/reports/courses_without_requests/(?P<year>\d{4}-\d{4})/(?P<term>.*)', views.get_courses_without_numberOfTARequests, name="get_courses_without_numberOfTARequests"),
    path('profile/', views.update_my_profile, name="update_my_profile"),
    path('profiles/', views.phds_profiles, name='phds_profiles'),
    re_path(r'profile/(?P<person_id>\d*)$', views.view_profile, name="view_profile"),
    re_path('apply/(?P<course_id>\d*)', views.apply, name="apply"),
    path('applications/my/', views.my_applications, name='my_applications'),
    re_path('applications/my/withdraw/(?P<application_id>\d*)', views.withdraw_application, name='withdraw_application'),
    path('applications/', views.get_applications_for_my_courses, name='applications_for_my_courses'),
    re_path('applications/review/(?P<application_id>\d*)', views.review_application, name='review_application'),
    path('config/', views.edit_config, name="edit_config"),
    path('config/add_phd', views.add_phd, name="add_phd"),
    path("config/batch_upload_phds", views.batch_upload_phds, name="batch_upload_phds"),
    path("config/batch_upload_phds_post", views.batch_upload_phds_ajax, name="batch_upload_phds_post"),
    re_path('reports/phds/(?P<year>\d{4}-\d{4})/(?P<term>(HIVER|ETE))', views.phds_report, name="phds_report"),
    re_path('reports/applications/(?P<year>\d{4}-\d{4})/(?P<term>.*)$', views.applications_list, name="applications_list"),
    re_path('applications/delete/(?P<application_id>\d*)', views.delete_application, name="delete_application"),
    re_path('reports/phds/download/(?P<year>\d{4}-\d{4})/(?P<term>(HIVER|ETE))', views.download_phds_report, name="download_phds_report"),
    path('reports/phds/multiple_hirings', views.phds_with_multiple_hirings_report, name='phds_with_multiple_hirings_report'),
    path('api/search/phds', views.autocomplete_phds, name="autocomplete_phds"),
    path('api/search/phds_in_app', views.autocomplete_phds_from_person, name="autocomplete_phds_from_person"),
    path('api/search/courses', views.autocomplete_courses, name="autocomplete_courses"),
    path('api/applications/get_details', views.get_course_applications_details, name="api_get_course_applications_details"),
    path('api/timereporting', timereporting_views.get_user_time_reports_api, name="get_user_time_reports_api"),
    re_path(r'api/timereporting/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))$', timereporting_views.get_time_reports_api, name="get_time_reports_api"),
    path('api/timereporting/my', timereporting_views.get_user_time_reports, name="get_user_time_reports"),
    re_path(r'api/timereporting/teacher/(?P<id>\d*)', timereporting_views.get_teacher, name="get_teacher"),
    re_path(r'api/timereporting/course/(?P<id>\d*)', timereporting_views.get_course, name="get_course"),
    path('assignments/add', views.add_assignment, name="add_assignment"),
    path('timereporting/', timereporting_views.get_user_time_reports, name="get_user_time_reports"),
    path('timereporting/reports/', timereporting_views.reports_entry_page, name="reports_entry_page"),
    path('api/timereporting/reports/years/', timereporting_views.get_reports_years, name="get_reports_years"),
    path('api/timereporting/reports/terms/', timereporting_views.get_reports_terms, name='get_reports_terms'),
    re_path(r'timereporting/reports/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))$', timereporting_views.get_time_reports, name="get_all_time_reports"),
    re_path(r'timereporting/reports/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))/charts$', timereporting_views.reports_charts, name="reports_charts"),
    re_path(r'api/timereporting/reports/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))/charts/chart_1', timereporting_views.get_data_for_report_chart_1, name="get_data_for_report_chart_1"),
    path('timereporting/add', timereporting_views.add_time_report, name="add_time_report"),
    re_path(r'timereporting/delete/(?P<id>\d*)', timereporting_views.delete_time_report, name="delete_time_report"),
    re_path(r'timereporting/edit/(?P<id>\d*)', timereporting_views.edit_time_report, name="edit_time_report"),
    path('api/search/my_courses', timereporting_views.autocomplete_my_courses, name="autocomplete_my_courses"),
    path('api/search/teachers', timereporting_views.autocomplete_all_teachers, name='autocomplete_all_teachers'),
    path('api/search/students', timereporting_views.autocomplete_all_students, name="autocomplete_all_students"),
    path('api/search/units', timereporting_views.autocomplete_all_units, name="autocomplete_all_units"),
    path('tools/mailer/new_campaign', mailer_views.new_mailer_campaign, name="new_mailer_campaign"),
    path('tools/mailer', mailer_views.get_mail_campaigns, name="get_mail_campaigns"),
    re_path(r'tools/mailer/campaign_details/(?P<id>\d*)', mailer_views.get_campaign_details, name="get_campaign_details"),
    path('api/tools/mailer/new_campaign_post', mailer_views.new_mailer_campaign_post, name="new_mailer_campaign_post"),
    path('api/tools/mailer/campaign/msg_preview', mailer_views.get_campaign_message_preview, name="get_campaign_message_preview"),
    path('api/tools/mailer/campaign/delete', mailer_views.delete_campaign, name="delete_campaign"),

    path('tools/applications', application_views.get_applications_html, name="get_applications_html"),
    path('tools/applications/new', application_views.new_application, name="new_application"),
    path('api/tools/applications/applicants', application_views.get_applicants, name="get_applicants"),
    path('api/tools/applications/courses', application_views.get_courses, name="get_courses"),
    path('api/tools/applications/status', application_views.get_applications_statuses, name="get_applications_statuses"),
    path('api/tools/applications/save', application_views.save_application_endpoint, name="save_application_endpoint"),
    path('api/tools/applications/delete', application_views.delete_application_endpoint, name="delete_application_endpoint"),
]

teaching_pool_project/web/forms/forms.py
import re

from django import forms
from django.db.models.functions import Lower
from django.forms import HiddenInput, ModelForm
from django.forms.widgets import SelectMultiple, Textarea

from web.models import *


class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)


class RequestForTA(forms.ModelForm):
    class Meta:
        model = NumberOfTAUpdateRequest
        fields = ("requestedNumberOfTAs", "requestReason")
        widgets = {
            "requestReason": Textarea(),
        }
        labels = {
            "requestReason": "Reason",
        }
        help_texts = {
            "requestReason": "Optionally, you can provide a reason for this request",
        }


class RequestForTAApproval(forms.Form):
    request_id = forms.IntegerField(widget=forms.HiddenInput)
    opened_at = forms.DateTimeField(disabled=True, required=False)
    requester = forms.CharField(disabled=True, required=False)
    course = forms.CharField(disabled=True, required=False)
    requestedNumberOfTAs = forms.IntegerField(
        disabled=True, label="Requested number of TAs", required=False
    )
    reason_for_request = forms.CharField(
        disabled=True, widget=forms.Textarea, required=False
    )
    reason_for_decision = forms.CharField(widget=forms.Textarea, required=False)


class RequestForTAView(forms.Form):
    request_id = forms.IntegerField(widget=forms.HiddenInput)
    opened_at = forms.DateTimeField(disabled=True, required=False)
    requester = forms.CharField(disabled=True, required=False)
    course = forms.CharField(disabled=True, required=False)
    requestedNumberOfTAs = forms.IntegerField(
        disabled=True, label="Requested number of TAs", required=False
    )
    reason_for_request = forms.CharField(
        disabled=True, widget=forms.Textarea, required=False
    )
    status = forms.CharField(disabled=True, required=False)
    reason_for_decision = forms.CharField(
        widget=forms.Textarea, required=False, disabled=True
    )


class AvailabilityForm(ModelForm):
    class Meta:
        model = Availability
        fields = "__all__"
        widgets = {
            "year": forms.HiddenInput(),
            "person": forms.HiddenInput(),
            "term": forms.HiddenInput(),
        }

    def clean(self):
        cleaned_data = super().clean()
        availability = cleaned_data["availability"].lower()
        reason = cleaned_data["reason"]
        if availability == "unavailable" and not reason:
            msg = "A reason should be provided when you say you will be unavailable."
            self.add_error("reason", msg)


class ApplicationForm_phd(ModelForm):
    class Meta:
        model = Applications
        fields = ["applicant", "course"]
        widgets = {"applicant": forms.HiddenInput(), "course": forms.HiddenInput()}


class ApplicationForm_teacher(ModelForm):
    class Meta:
        model = Applications
        fields = "__all__"
        exclude = ["openedAt", "status", "closedAt", "closedBy"]
        labels = {
            "applicant": "PhD",
            "decisionReason": "Reason for decision",
        }
        widgets = {
            "applicant": forms.HiddenInput(),
            "course": forms.HiddenInput(),
        }


class LanguagesForm(forms.Form):
    OPTIONS = (("f", "French"), ("e", "English"), ("g", "German"))
    languages = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, choices=OPTIONS
    )

    def clean(self):
        cleaned_data = super().clean()
        possible_choices = [item[0] for item in self.fields["languages"].choices]
        if "languages" in cleaned_data:
            for language in cleaned_data["languages"]:
                if language not in possible_choices:
                    self.add_error(
                        "languages",
                        "The value provided is not part of the available choices.",
                    )
        else:
            self.add_error(
                "languages", "You should be able to teach at least in one language"
            )


class TopicForm(ModelForm):
    class Meta:
        model = Person
        fields = ("topics",)

    def __init__(self, *args, **kwargs):
        super(TopicForm, self).__init__(*args, **kwargs)

        self.fields["topics"].widget = SelectMultiple(attrs={"size": 20})
        self.fields["topics"].queryset = Topic.objects.order_by(Lower("name")).all()
        self.fields[
            "topics"
        ].help_text = "Don't forget to hold the CTRL key (or cmd on a Mac) to select multiple topics"


class ConfigForm(ModelForm):
    class Meta:
        model = Config
        fields = "__all__"


class PeopleManagementForm(forms.Form):
    add_person = forms.CharField(max_length=255)

    class Meta:
        labels = {
            "add_person": "SCIPER or username",
        }

    def __init__(self, *args, **kwargs):
        super(PeopleManagementForm, self).__init__(*args, **kwargs)

        self.fields["add_person"].label = "Name or sciper"
        self.fields[
            "add_person"
        ].help_text = "You can search the person by sciper or by name"

    def clean(self):
        cleaned_data = super().clean()
        pattern = r".*,\s.*\((\d*)\)"
        if not re.match(pattern, cleaned_data["add_person"]):
            self.add_error(
                "add_person",
                "The value passed is not correct. It should be <last name>, <first name> (<sciper>)",
            )


class AssignmentManagementForm(forms.Form):
    person = forms.CharField(max_length=255)
    course = forms.CharField(max_length=255)

    class Meta:
        labels = {
            "person": "SCIPER or username",
            "course": "course code or subject",
            "role": "Role",
        }

    def __init__(self, *args, **kwargs):
        super(AssignmentManagementForm, self).__init__(*args, **kwargs)

        self.fields["person"].label = "Name or sciper"
        self.fields[
            "person"
        ].help_text = "You can search the person by sciper or by name"
        self.fields["course"].label = "Code or subject"
        self.fields["course"].help_text = "You can search the course by code or subject"

    def clean(self):
        cleaned_data = super().clean()
        person_pattern = r".*,\s.*\((\d*)\)"
        if not re.match(person_pattern, cleaned_data["person"]):
            self.add_error(
                "person",
                "The value passed is not correct. It should be <last name>, <first name> (<sciper>)",
            )
        course_pattern = r"^.*\s\(.*\)$"
        if not re.match(course_pattern, cleaned_data["course"]):
            self.add_error(
                "course",
                "The value passed is not correct. It should be <subject>(<code>)",
            )

teaching_pool_project/web/templates/web/_nav.html
{% load extra_tags %}
{% load _nav_tags %}
{% with url_name=request.resolver_match.url_name %}
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="{% url "web:index" %}">Teaching pools</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if url_name == "index" %}active{% endif %}">
        <a class="nav-link" href="{% url "web:index" %}">Home{% if url_name == "index" %} <span class="sr-only">(current)</span>{% endif %}</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Courses
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url "web:courses_full_list" year=CURRENT_YEAR %}">All courses ({{ CURRENT_YEAR }})</a>
          {% if request.user|has_group:"teachers" %}
          <a class="dropdown-item" href="{% url "web:courses_list_year_teacher" year=CURRENT_YEAR %}">My courses</a>
          <a class="dropdown-item" href="{% url "web:applications_for_my_courses" %}">Applications for my courses</a>

          {% endif %}
      </li>

      {% if request.user|is_staff_or_teacher %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Students
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url "web:add_phd" %}">Add student</a>
        <a class="dropdown-item" href="{% url "web:add_assignment" %}">Enroll student</a>
        {% if request.user|is_staff %}
          <a class="dropdown-item" href="{% url "web:phds_profiles" %}">All profiles</a>
          <a class="dropdown-item" href="{% url "web:applications_list" year=CURRENT_YEAR term=CURRENT_TERM %}">All applications</a>
          <a class="dropdown-item" href="{% url "web:phds_report" CURRENT_YEAR CURRENT_TERM %}">Applications status per PhD</a>
        {% endif %}
        {% comment %} <a class="dropdown-item" href="{% url "web:phds_with_multiple_hirings_report" %}">Multiple acceptance</a> {% endcomment %}
      </li>
      {% endif %}

      {% if request.user|is_phd %}
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if url_name == "get_user_time_reports" %}active{% endif %}">
          <a class="nav-link" href="{% url "web:get_user_time_reports" %}">Time reporting{% if url_name == "get_user_time_reports" %} <span class="sr-only">(current)</span>{% endif %}</a>
        </li>
      </ul>
      {% endif %}

      {% if request.user|is_staff or request.user|is_teacher %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Requests
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.user|is_staff %}
          <a class="dropdown-item" href="{% url "web:get_TAs_requests_to_validate" %}">Teaching assistants (to be validated)</a>
          <a class="dropdown-item" href="{% url "web:get_courses_without_numberOfTARequests" year=CURRENT_YEAR term=CURRENT_TERM %}">Courses without TAs requests</a>
          {% endif %}
          {% if request.user|has_group:"teachers" %}
          <a class="dropdown-item" href="{% url "web:requests_for_tas_teacher" %}">My requests (all)</a>
          <a class="dropdown-item" href="{% url "web:requests_for_tas_teacher_status" status="Pending" %}">My requests (pending)</a>
          <a class="dropdown-item" href="{% url "web:requests_for_tas_teacher_status" status="Approved" %}">My requests (approved)</a>
          <a class="dropdown-item" href="{% url "web:requests_for_tas_teacher_status" status="Declined" %}">My requests (declined)</a>
          {% endif %}
          {% if request.user|is_staff %}
          <a class="dropdown-item" href="{% url "web:courses_report" year=CURRENT_YEAR term=CURRENT_TERM %}">Status of all courses</a>
          {% endif %}
      </li>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if url_name == "reports_entry_page" %}active{% endif %}">
          <a class="nav-link" href="{% url "web:reports_entry_page" %}">Time reporting{% if url_name == "reports_entry_page" %} <span class="sr-only">(current)</span>{% endif %}</a>
        </li>
      </ul>
      {% endif %}
    </ul>
    {% if request.user.is_authenticated %}
      {% if request.user|is_phd %}
          <div class="dropdown show">
            <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ request.user|get_badge }}
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url "web:update_my_profile" %}">Profile</a>
              <a class="dropdown-item" href="{% url "web:my_applications" %}">Applications</a>
            </div>
          </div>
      {% elif request.user|is_staff %}
        <div class="dropdown show">
            <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.user|get_badge }}
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url "web:edit_config" %}">Configuration</a>
              <a class="dropdown-item" href="{% url "web:batch_upload_phds" %}">Batch add phds</a>
              <a class="dropdown-item" href="{% url "web:get_mail_campaigns" %}">Mailer</a>
              {% if request.user.is_superuser %}
              <a class="dropdown-item" href="{% url "web:get_applications_html" %}">Applications</a>
              {% endif %}
            </div>
      {% else %}
        {{ request.user|get_badge }}
      {% endif %}
    {% endif %}
  </div>
  <div style="padding-left:5px;">
    <a href="https://inside.epfl.ch/sti-ta/sti-teaching-assistants-welcome/" class="btn btn-info" role="button" target="_blank"><i class="fas fa-book-open"></i>&nbsp; FAQ</a>
    <a href="mailto:TA_STI@epfl.ch" class="btn btn-danger" role="button"><i class="fas fa-medkit"></i>&nbsp;Help</a>
  </div>
</nav>
{% endwith %}

teaching_pool_project/web/templates/web/add_phd_form.html
{% extends "web/base.html" %}
{% load bootstrap4 %}
{% load course_tags %}

{% block headers %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" type="text/css" media="all">
{% endblock headers%}

{% block maincontent %}
<form action="{% url "web:add_phd" %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form=form %}
    {% buttons %}
    {% bootstrap_button "Add" button_type="submit" button_class="btn-success btn-block" %}
    {% endbuttons %}
</form>
{% endblock maincontent %}


{% block scripts %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $("#id_add_person").autocomplete({
        source: "{% url "web:autocomplete_phds" %}",
        minLength: 2,
        open: function(){
            setTimeout(function () {
                $('.ui-autocomplete').css('z-index', 99);
            }, 0);
        },
        select: function(event, ui){
            console.log(ui.item.value);
        }
        });
});
</script>
{% endblock scripts %}

teaching_pool_project/web/templates/web/application_form.html
{% extends "web/base.html" %}
{% load bootstrap4 %}
{% load course_tags %}

{% block maincontent %}
<form action="{% url "web:apply" course_id=course.pk  %}" method="post" class="form">
    {% csrf_token %}
    <div class="card">
        <div class="card-header">
            <h6>{{ course.subject }} ({{ course.code }})<h6>
        </div>
        <div class="card-body">
            <p>Term: {{ course.term }}</p>
            <p>Teacher(s): <span class="teachers">{{ course|format_teachers }}</span></p>
            <p>Form(s): {{ course|format_forms }}</p>
            <p>Language(s): {{ course|format_languages }}</p>
            {% bootstrap_form form=form %}
        </div>
    </div>
    <div>
        {% buttons %}
        {% bootstrap_button "Apply" button_type="submit" button_class="btn-success btn-block" %}
        <a class="btn btn-danger btn-block" href="{% url 'web:courses_full_list' year=course.year %}">Back to courses</a>
        {% endbuttons %}
    </div>
</form>
{% endblock maincontent %}

teaching_pool_project/web/templates/web/blank.html
{% extends "web/base.html" %} {% load bootstrap4 %}
{% block maincontent %}
{% endblock maincontent %}

teaching_pool_project/web/templates/web/index.html
{% extends "web/base.html" %} {% load bootstrap4 %} {% block maincontent %}
{% load extra_tags %}

<div class="jumbotron">
    <h1 class="display-3">Teaching Pools</h1>
    <p class="lead">Where teaching assistants positions can be filled.</p>
  </div>

    <div class="alert alert-info" role="alert"><i class="fa fa-shoe-prints fa-2x " aria-hidden="true" style="vertical-align: middle;"></i>&nbsp; Next steps</div>

  <div class="row">
    <div class="col">
      <div class="card-columns list">

      {% if request.user|is_teacher or request.user|is_superuser %}
      <div class="card">
        <div class="card-header">As a teacher, you can</div>
        <div class="card-body">
          <ul>
              <li><a href="https://inside.epfl.ch/sti-ta/sti-teaching-assistants-welcome/" target="_blank">Read the documentation</a></li>
              <li><a href="{% url "web:courses_list_year_teacher" year=CURRENT_YEAR %}" role="button">Review your courses</a></li>
              <li><a href="{% url "web:requests_for_tas_teacher" %}">View your request(s) for Teaching Assistants</a></li>
              <li><a href='{% url "web:applications_for_my_courses" %}'>Review the applications to your course(s)</a></li>
          </ul>
        </div>
      </div>
      {% endif %}

    {% if request.user|is_phd or request.user|is_superuser %}
    <div class="card">
        <div class="card-header">As a PhD, you can</div>
        <div class="card-body">
          <ul>
            <li><a href="https://inside.epfl.ch/sti-ta/sti-teaching-assistants-welcome/" target="_blank">Read the documentation</a></li>
            <li><a href="{% url "web:update_my_profile" %}" role="button">Update your profile</a></li>
            {% if APPLICATIONS_ARE_OPEN %}
            <li><a href="{% url "web:courses_full_list" year=CURRENT_YEAR %}">Apply for teaching assistant positions</a></li>
            {% endif %}
            <li><a href='{% url "web:my_applications" %}'>Review your application(s)</a></li>
            <li><a href='{% url "web:get_user_time_reports" %}'>Report the time you spent on the TA duties</a></li>
          </ul>
        </div>
    </div>
    {% endif %}

    {% if request.user|is_staff or request.user|is_superuser %}
    <div class="card">
        <div class="card-header">As a staff member, you can</div>
        <div class="card-body">
          <ul>
            <li><a href="https://inside.epfl.ch/sti-ta/sti-teaching-assistants-welcome/" target="_blank">Read the documentation</a></li>
            <li><a href="{% url "web:get_TAs_requests_to_validate" %}" role="button">Review the requests for Teaching Assistants</a></li>
            <li><a href="{% url "web:courses_report" year=CURRENT_YEAR term=CURRENT_TERM %}" role="button">Review the status of all courses</a></li>
            <li><a href="{% url "web:reports_entry_page" %}">Review the time reporting</a></li>
          </ul>
        </div>
    </div>
    {% endif %}
{% endblock maincontent %}