teaching_pool_project/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

app_name = 'api'

urlpatterns = {
    url(r'v1/persons/', Persons.as_view(), name="persons"),
    url(r'v1/person/?(?P<pk>[^/]+)/$', PersonDetail.as_view(), name="person_details"),
    url(r'v1/courses/', Courses.as_view(), name="courses"),
    url(r'v1/course/(?P<pk>\d*)/$', CourseDetail.as_view(), name="course_details_by_id"),
    url(r'v1/course/(?P<year>.*)/(?P<term>.*)/(?P<code>.*)/$', CourseDetailByYearTermCode.as_view(), name="course_details_by_year_term_code"),
    url(r'v1/teachings/$', Teachings.as_view(), name="teachings"),
    url(r'v1/teachings/(?P<sciper>\d*)/$', TeachingsBySciper.as_view(), name="teachings_by_sciper")
}

urlpatterns = format_suffix_patterns(urlpatterns)

teaching_pool_project/teaching_pool_project/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_tequila.urls import urlpatterns as django_tequila_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('web.urls')),
    path('api/', include('api.urls')),
]
urlpatterns += django_tequila_urlpatterns

if settings.DEBUG:
    print("importing debug_toolbar")
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

teaching_pool_project/web/urls.py
from django.urls import path, re_path

from web.views import views, timereporting_views, mailer_views, application_views

app_name = 'web'

urlpatterns = [
    path('', views.index, name="index"),
    re_path(r'courses/(?P<year>\d{4}-\d{4})$', views.courses_full_list, name="courses_full_list"),
    re_path(r'courses/(?P<year>\d{4}-\d{4})/my', views.courses_list_year_teacher, name="courses_list_year_teacher"),
    re_path(r'TAs/request/(?P<course_id>\d*$)', views.request_for_TA, name="request_for_TA"),
    re_path(r'TAs/accept/(?P<course_id>\d*$)', views.accept_theoretical_number_of_tas, name="accept_theoretical_number_of_tas"),
    path('requests/TAs/', views.get_TAs_requests_to_validate, name="get_TAs_requests_to_validate"),
    re_path(r'requests/TAs/review/(?P<request_id>\d*$)', views.validate_request_for_TA, name="validate_request_for_TA"),
    re_path(r'requests/TAs/view/(?P<request_id>\d*$)', views.view_request_for_TA, name="view_request_for_TA"),
    path('requests/TAs/my/', views.requests_for_tas_teacher, name="requests_for_tas_teacher"),
    re_path(r'requests/TAs/my/(?P<status>.*$)', views.requests_for_tas_teacher_status, name="requests_for_tas_teacher_status"),
    re_path(r'requests/TAs/reports/full_list/(?P<year>\d{4}-\d{4})/(?P<term>.*)$', views.courses_report, name="courses_report"),
    re_path(r'requests/TAs/reports/full_list/(?P<year>\d{4}-\d{4})/(?P<term>.*)/download/$', views.download_course_report, name="download_course_report"),
    re_path('requests/TAs/reports/courses_without_requests/(?P<year>\d{4}-\d{4})/(?P<term>.*)', views.get_courses_without_numberOfTARequests, name="get_courses_without_numberOfTARequests"),
    path('profile/', views.update_my_profile, name="update_my_profile"),
    path('profiles/', views.phds_profiles, name='phds_profiles'),
    re_path(r'profile/(?P<person_id>\d*)$', views.view_profile, name="view_profile"),
    re_path('apply/(?P<course_id>\d*)', views.apply, name="apply"),
    path('applications/my/', views.my_applications, name='my_applications'),
    re_path('applications/my/withdraw/(?P<application_id>\d*)', views.withdraw_application, name='withdraw_application'),
    path('applications/', views.get_applications_for_my_courses, name='applications_for_my_courses'),
    re_path('applications/review/(?P<application_id>\d*)', views.review_application, name='review_application'),
    path('config/', views.edit_config, name="edit_config"),
    path('config/add_phd', views.add_phd, name="add_phd"),
    path("config/batch_upload_phds", views.batch_upload_phds, name="batch_upload_phds"),
    path("config/batch_upload_phds_post", views.batch_upload_phds_ajax, name="batch_upload_phds_post"),
    re_path('reports/phds/(?P<year>\d{4}-\d{4})/(?P<term>(HIVER|ETE))', views.phds_report, name="phds_report"),
    re_path('reports/applications/(?P<year>\d{4}-\d{4})/(?P<term>.*)$', views.applications_list, name="applications_list"),
    re_path('applications/delete/(?P<application_id>\d*)', views.delete_application, name="delete_application"),
    re_path('reports/phds/download/(?P<year>\d{4}-\d{4})/(?P<term>(HIVER|ETE))', views.download_phds_report, name="download_phds_report"),
    path('reports/phds/multiple_hirings', views.phds_with_multiple_hirings_report, name='phds_with_multiple_hirings_report'),
    path('api/search/phds', views.autocomplete_phds, name="autocomplete_phds"),
    path('api/search/phds_in_app', views.autocomplete_phds_from_person, name="autocomplete_phds_from_person"),
    path('api/search/courses', views.autocomplete_courses, name="autocomplete_courses"),
    path('api/applications/get_details', views.get_course_applications_details, name="api_get_course_applications_details"),
    path('api/timereporting', timereporting_views.get_user_time_reports_api, name="get_user_time_reports_api"),
    re_path(r'api/timereporting/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))$', timereporting_views.get_time_reports_api, name="get_time_reports_api"),
    path('api/timereporting/my', timereporting_views.get_user_time_reports, name="get_user_time_reports"),
    re_path(r'api/timereporting/teacher/(?P<id>\d*)', timereporting_views.get_teacher, name="get_teacher"),
    re_path(r'api/timereporting/course/(?P<id>\d*)', timereporting_views.get_course, name="get_course"),
    path('assignments/add', views.add_assignment, name="add_assignment"),
    path('timereporting/', timereporting_views.get_user_time_reports, name="get_user_time_reports"),
    path('timereporting/reports/', timereporting_views.reports_entry_page, name="reports_entry_page"),
    path('api/timereporting/reports/years/', timereporting_views.get_reports_years, name="get_reports_years"),
    path('api/timereporting/reports/terms/', timereporting_views.get_reports_terms, name='get_reports_terms'),
    re_path(r'timereporting/reports/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))$', timereporting_views.get_time_reports, name="get_all_time_reports"),
    re_path(r'timereporting/reports/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))/charts$', timereporting_views.reports_charts, name="reports_charts"),
    re_path(r'api/timereporting/reports/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))/charts/chart_1', timereporting_views.get_data_for_report_chart_1, name="get_data_for_report_chart_1"),
    path('timereporting/add', timereporting_views.add_time_report, name="add_time_report"),
    re_path(r'timereporting/delete/(?P<id>\d*)', timereporting_views.delete_time_report, name="delete_time_report"),
    re_path(r'timereporting/edit/(?P<id>\d*)', timereporting_views.edit_time_report, name="edit_time_report"),
    path('api/search/my_courses', timereporting_views.autocomplete_my_courses, name="autocomplete_my_courses"),
    path('api/search/teachers', timereporting_views.autocomplete_all_teachers, name='autocomplete_all_teachers'),
    path('api/search/students', timereporting_views.autocomplete_all_students, name="autocomplete_all_students"),
    path('api/search/units', timereporting_views.autocomplete_all_units, name="autocomplete_all_units"),
    path('tools/mailer/new_campaign', mailer_views.new_mailer_campaign, name="new_mailer_campaign"),
    path('tools/mailer', mailer_views.get_mail_campaigns, name="get_mail_campaigns"),
    re_path(r'tools/mailer/campaign_details/(?P<id>\d*)', mailer_views.get_campaign_details, name="get_campaign_details"),
    path('api/tools/mailer/new_campaign_post', mailer_views.new_mailer_campaign_post, name="new_mailer_campaign_post"),
    path('api/tools/mailer/campaign/msg_preview', mailer_views.get_campaign_message_preview, name="get_campaign_message_preview"),
    path('api/tools/mailer/campaign/delete', mailer_views.delete_campaign, name="delete_campaign"),

    path('tools/applications', application_views.get_applications_html, name="get_applications_html"),
    path('tools/applications/new', application_views.new_application, name="new_application"),
    path('api/tools/applications/applicants', application_views.get_applicants, name="get_applicants"),
    path('api/tools/applications/courses', application_views.get_courses, name="get_courses"),
    path('api/tools/applications/status', application_views.get_applications_statuses, name="get_applications_statuses"),
    path('api/tools/applications/save', application_views.save_application_endpoint, name="save_application_endpoint"),
    path('api/tools/applications/delete', application_views.delete_application_endpoint, name="delete_application_endpoint"),
]

teaching_pool_project/web/views/application_views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import logging
import re
from datetime import date, datetime
import datetime
from functools import wraps

import pandas as pd
import xlwt
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group, User
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models import ExpressionWrapper, F, IntegerField, Prefetch, Q, Value
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template import Context
from django.template.loader import get_template
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from django.views import generic

from epfl.sti.helpers import ldap as epfl_ldap
from web.forms.timereporting_forms import *
from web.helpers import config
from web.models import *

logger = logging.getLogger(__name__)

User = get_user_model()


def is_superuser():
    def has_superuser_profile(u):
        logger.debug("Checking if %s is superuser", u.username)
        if u.is_superuser:
            return True
        raise PermissionDenied

    return user_passes_test(has_superuser_profile)


def is_staff():
    def has_staff_profile(u):
        logger.debug("Checking if %s is staff", u.username)
        if u.is_staff:
            return True
        raise PermissionDenied

    return user_passes_test(has_staff_profile)


def is_staff_or_teacher():
    def has_staff_or_teacher_profile(u):
        if u.is_superuser:
            return True
        elif u.is_staff:
            return True
        elif u.groups.filter(name="teachers").exists():
            return True
        else:
            raise PermissionDenied

    return user_passes_test(has_staff_or_teacher_profile)


def group_required(*group_names):
    """Requires user membership in at least one of the groups passed in."""

    def in_groups(u):
        logger.debug(
            "Checking if %s is member of the '%s' group(s)", u.username, group_names
        )
        if u.is_authenticated:
            if bool(u.groups.filter(name__in=group_names)) | u.is_superuser:
                return True
        raise PermissionDenied

    return user_passes_test(in_groups)


@is_superuser()
def get_courses(request):
    pass


@is_superuser()
def new_application(request):
    context = {}
    return render(request, "web/applications/new.html", context=context)


@is_superuser()
def get_applicants(request):
    if request.is_ajax():
        term = request.GET.get("term", None)
        data = []
        phds = Group.objects.get(name="phds").user_set.all()
        if term:
            phds = phds.filter(
                Q(last_name__icontains=term)
                | Q(first_name__icontains=term)
                | Q(sciper__icontains=term)
            ).all()
        for phd in phds:
            current_entry = {
                "id": phd.pk,
                "text": "{}, {} ({})".format(phd.last_name, phd.first_name, phd.sciper),
            }
            data.append(current_entry)
        response = {"items": data}
        return JsonResponse(response)


@is_superuser()
def get_courses(request):
    if request.is_ajax():
        term = request.GET.get("term", None)
        data = []
        courses = Course.objects.order_by("year", "term").all()
        if term:
            courses = (
                courses.filter(Q(subject__icontains=term) | Q(code__icontains=term))
                .order_by("year", "term")
                .all()
            )

        previous_group_text = ""
        current_group = None

        for course in courses:
            current_group_text = "{} - {}".format(course.year, course.term)
            if current_group_text != previous_group_text:
                if current_group:
                    data.append(current_group)
                current_group = {"text": current_group_text, "children": []}
                previous_group_text = current_group_text

            current_entry = {
                "id": course.pk,
                "text": "{} ({})".format(course.subject, course.code),
            }
            current_group["children"].append(current_entry)

        response = {"items": data}
        return JsonResponse(response)


@is_superuser()
def get_applications_statuses(request):
    if request.is_ajax():
        result = []
        for status in Applications.STATUS_CHOICES:
            result.append({"id": status[0], "text": status[1]})
        return JsonResponse({"items": result})


@is_superuser()
def save_application_endpoint(request):
    if request.is_ajax():
        applicant_id = request.POST.get("applicant", None)
        course_id = request.POST.get("course", None)
        status = request.POST.get("status", None)

        try:
            applicant = Person.objects.get(pk=applicant_id)
            course = Course.objects.get(pk=course_id)
            application, created = Applications.objects.get_or_create(
                applicant=applicant, course=course
            )
            application.applicant = applicant
            application.course = course
            application.createdAt = now()
            application.createdBy = request.user
            application.status = status
            application.closedAt = now()
            application.closedBy = request.user
            application.save()

            operation_status = "ok"
            if created == True:
                msg = "Application successfully created"
            else:
                msg = "Application successfully updated"
        except Exception as ex:
            logger.exception("Unable to save application")
            operation_status = "error"
            msg = str(ex)

        return JsonResponse({"status": operation_status, "msg": msg})


@is_superuser()
def get_applications_html(request):
    applications = (
        Applications.objects.all()
        .order_by("-openedAt")
        .select_related("applicant", "course",)
    )
    context = {"applications": applications}
    return render(request, "web/applications/list.html", context=context)


@is_superuser()
def delete_application_endpoint(request):
    if request.is_ajax():
        id = request.POST.get("id", None)
        application = Applications.objects.get(pk=id)
        application.delete()
        msg = "ok"
        return JsonResponse({"msg": msg, "id": id})

teaching_pool_project/web/templates/web/applications/list.html
{% extends "web/base.html" %}
{% load bootstrap4 %}
{% load extra_tags %}
{% load static %}
{% block headers%}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
{% endblock headers%}

{% block maincontent %}
<h1>Applications</h1>
<table class="table table-striped table-hover" id="applications">
    <thead class="thead-dark">
        <tr>
            <th>id</th>
            <th>Created at</th>
            <th>Applicant</th>
            <th>Course</th>
            <th>Closed at</th>
            <th>Closed by</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for application in applications %}
        <tr data-application-id="{{ application.id }}">
            <td>{{ application.id }}</td>
            <td>{{ application.openedAt.isoformat }}</td>
            <td>{{ application.applicant.last_name}}, {{ application.applicant.first_name }}</td>
            <td>{{ application.course.subject }} ({{ application.course.code }})</td>
            <td>{{ application.closedAt.isoformat|default_if_none:"" }} </td>
            <td>{% if application.closedBy %}{{ application.closedBy.last_name }}, {{ application.closedBy.first_name }}{% else %}&nbsp;{% endif %}</td>
            <td>{{ application.status }}</td>
            <td><button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal" data-id="{{ application.id }}"><i class="far fa-trash-alt"></i></button></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<a class="btn btn-primary" href="{% url 'web:new_application' %}">New application</a>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>are you sure you want to delete this application?</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-danger bt-sm button-confirm">Yes</button>
      </div>
    </div>
  </div>
</div>

{% endblock maincontent %}

{% block scripts %}
<script>
    let csrf_token = "{{ csrf_token }}";
    let delete_url = "{% url "web:delete_application_endpoint" %}";
</script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="{% static 'web/js/moment.min.js' %}"></script>
<script src="{% static 'web/js/applications/list.js' %}"></script>
{% endblock scripts %}

teaching_pool_project/web/templates/web/applications/new.html
{% extends "web/base.html" %}
{% load bootstrap4 %}
{% load extra_tags %}
{% load static %}

{% block headers %}
<link rel="stylesheet" href="{% static 'web/css/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css' %}" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
{% endblock headers %}
{% block maincontent %}
<h1>New application</h1>
<div id="output" class="alert" role="alert"></div>
<form id="form">
    <div class="form-group">
        <label for="applicantInputGroup">Applicant</label>
        <div class='input-group' id='applicantInputGroup' aria-describedby="applicantHelp">
            <select required class="form-control" id="applicant"></select>
        </div>
        <small id="applicantHelper" class="form-text text-muted">Name or sciper of the applicant</small>
    </div>
    <div class="form-group">
        <label for="courseInputGroup">Course</label>
        <div class='input-group' id='courseInputGroup' aria-describedby="courseHelp">
            <select required class="form-control" id="course"></select>
        </div>
        <small id="courseHelp" class="form-text text-muted">subject or code of the course</small>
    </div>
        <div class="form-group">
        <label for="statusInputGroup">Status</label>
        <div class='input-group' id='statusInputGroup' aria-describedby="statusHelp">
            <select required class="form-control" id="status"></select>
        </div>
        <small id="statusHelp" class="form-text text-muted">status of the application</small>
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit" form="form" value="Submit">Save</button>
        <a class="btn btn-secondary" href="{% url "web:get_applications_html" %}">Back to list</a>
    </div>
</form>
{% endblock maincontent %}

{% block scripts %}
<script src="{% static 'web/js/forms/mailer/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'web/js/moment.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script>
    let applicants_endpoint = '{% url "web:get_applicants" %}';
    let courses_endpoint = '{% url "web:get_courses" %}';
    let status_endpoint = '{% url "web:get_applications_statuses" %}';
    let post_endpoint = '{% url "web:save_application_endpoint" %}';
    let csrf_token = '{{csrf_token }}';
</script>
<script type="text/javascript" src="{% static 'web/js/applications/new.js' %}"></script>
{% endblock scripts %}