teaching_pool_project/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

app_name = 'api'

urlpatterns = {
    url(r'v1/persons/', Persons.as_view(), name="persons"),
    url(r'v1/person/?(?P<pk>[^/]+)/$', PersonDetail.as_view(), name="person_details"),
    url(r'v1/courses/', Courses.as_view(), name="courses"),
    url(r'v1/course/(?P<pk>\d*)/$', CourseDetail.as_view(), name="course_details_by_id"),
    url(r'v1/course/(?P<year>.*)/(?P<term>.*)/(?P<code>.*)/$', CourseDetailByYearTermCode.as_view(), name="course_details_by_year_term_code"),
    url(r'v1/teachings/$', Teachings.as_view(), name="teachings"),
    url(r'v1/teachings/(?P<sciper>\d*)/$', TeachingsBySciper.as_view(), name="teachings_by_sciper")
}

urlpatterns = format_suffix_patterns(urlpatterns)

teaching_pool_project/teaching_pool_project/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_tequila.urls import urlpatterns as django_tequila_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('web.urls')),
    path('api/', include('api.urls')),
]
urlpatterns += django_tequila_urlpatterns

if settings.DEBUG:
    print("importing debug_toolbar")
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

teaching_pool_project/web/urls.py
from django.urls import path, re_path

from web.views import views, timereporting_views, mailer_views, application_views

app_name = 'web'

urlpatterns = [
    path('', views.index, name="index"),
    re_path(r'courses/(?P<year>\d{4}-\d{4})$', views.courses_full_list, name="courses_full_list"),
    re_path(r'courses/(?P<year>\d{4}-\d{4})/my', views.courses_list_year_teacher, name="courses_list_year_teacher"),
    re_path(r'TAs/request/(?P<course_id>\d*$)', views.request_for_TA, name="request_for_TA"),
    re_path(r'TAs/accept/(?P<course_id>\d*$)', views.accept_theoretical_number_of_tas, name="accept_theoretical_number_of_tas"),
    path('requests/TAs/', views.get_TAs_requests_to_validate, name="get_TAs_requests_to_validate"),
    re_path(r'requests/TAs/review/(?P<request_id>\d*$)', views.validate_request_for_TA, name="validate_request_for_TA"),
    re_path(r'requests/TAs/view/(?P<request_id>\d*$)', views.view_request_for_TA, name="view_request_for_TA"),
    path('requests/TAs/my/', views.requests_for_tas_teacher, name="requests_for_tas_teacher"),
    re_path(r'requests/TAs/my/(?P<status>.*$)', views.requests_for_tas_teacher_status, name="requests_for_tas_teacher_status"),
    re_path(r'requests/TAs/reports/full_list/(?P<year>\d{4}-\d{4})/(?P<term>.*)$', views.courses_report, name="courses_report"),
    re_path(r'requests/TAs/reports/full_list/(?P<year>\d{4}-\d{4})/(?P<term>.*)/download/$', views.download_course_report, name="download_course_report"),
    re_path('requests/TAs/reports/courses_without_requests/(?P<year>\d{4}-\d{4})/(?P<term>.*)', views.get_courses_without_numberOfTARequests, name="get_courses_without_numberOfTARequests"),
    path('profile/', views.update_my_profile, name="update_my_profile"),
    path('profiles/', views.phds_profiles, name='phds_profiles'),
    re_path(r'profile/(?P<person_id>\d*)$', views.view_profile, name="view_profile"),
    re_path('apply/(?P<course_id>\d*)', views.apply, name="apply"),
    path('applications/my/', views.my_applications, name='my_applications'),
    re_path('applications/my/withdraw/(?P<application_id>\d*)', views.withdraw_application, name='withdraw_application'),
    path('applications/', views.get_applications_for_my_courses, name='applications_for_my_courses'),
    re_path('applications/review/(?P<application_id>\d*)', views.review_application, name='review_application'),
    path('config/', views.edit_config, name="edit_config"),
    path('config/add_phd', views.add_phd, name="add_phd"),
    path("config/batch_upload_phds", views.batch_upload_phds, name="batch_upload_phds"),
    path("config/batch_upload_phds_post", views.batch_upload_phds_ajax, name="batch_upload_phds_post"),
    re_path('reports/phds/(?P<year>\d{4}-\d{4})/(?P<term>(HIVER|ETE))', views.phds_report, name="phds_report"),
    re_path('reports/applications/(?P<year>\d{4}-\d{4})/(?P<term>.*)$', views.applications_list, name="applications_list"),
    re_path('applications/delete/(?P<application_id>\d*)', views.delete_application, name="delete_application"),
    re_path('reports/phds/download/(?P<year>\d{4}-\d{4})/(?P<term>(HIVER|ETE))', views.download_phds_report, name="download_phds_report"),
    path('reports/phds/multiple_hirings', views.phds_with_multiple_hirings_report, name='phds_with_multiple_hirings_report'),
    path('api/search/phds', views.autocomplete_phds, name="autocomplete_phds"),
    path('api/search/phds_in_app', views.autocomplete_phds_from_person, name="autocomplete_phds_from_person"),
    path('api/search/courses', views.autocomplete_courses, name="autocomplete_courses"),
    path('api/applications/get_details', views.get_course_applications_details, name="api_get_course_applications_details"),
    path('api/timereporting', timereporting_views.get_user_time_reports_api, name="get_user_time_reports_api"),
    re_path(r'api/timereporting/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))$', timereporting_views.get_time_reports_api, name="get_time_reports_api"),
    path('api/timereporting/my', timereporting_views.get_user_time_reports, name="get_user_time_reports"),
    re_path(r'api/timereporting/teacher/(?P<id>\d*)', timereporting_views.get_teacher, name="get_teacher"),
    re_path(r'api/timereporting/course/(?P<id>\d*)', timereporting_views.get_course, name="get_course"),
    path('assignments/add', views.add_assignment, name="add_assignment"),
    path('timereporting/', timereporting_views.get_user_time_reports, name="get_user_time_reports"),
    path('timereporting/reports/', timereporting_views.reports_entry_page, name="reports_entry_page"),
    path('api/timereporting/reports/years/', timereporting_views.get_reports_years, name="get_reports_years"),
    path('api/timereporting/reports/terms/', timereporting_views.get_reports_terms, name='get_reports_terms'),
    re_path(r'timereporting/reports/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))$', timereporting_views.get_time_reports, name="get_all_time_reports"),
    re_path(r'timereporting/reports/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))/charts$', timereporting_views.reports_charts, name="reports_charts"),
    re_path(r'api/timereporting/reports/(?P<year>\d{4}-\d{4})/(?P<term>(winter|summer))/charts/chart_1', timereporting_views.get_data_for_report_chart_1, name="get_data_for_report_chart_1"),
    path('timereporting/add', timereporting_views.add_time_report, name="add_time_report"),
    re_path(r'timereporting/delete/(?P<id>\d*)', timereporting_views.delete_time_report, name="delete_time_report"),
    re_path(r'timereporting/edit/(?P<id>\d*)', timereporting_views.edit_time_report, name="edit_time_report"),
    path('api/search/my_courses', timereporting_views.autocomplete_my_courses, name="autocomplete_my_courses"),
    path('api/search/teachers', timereporting_views.autocomplete_all_teachers, name='autocomplete_all_teachers'),
    path('api/search/students', timereporting_views.autocomplete_all_students, name="autocomplete_all_students"),
    path('api/search/units', timereporting_views.autocomplete_all_units, name="autocomplete_all_units"),
    path('tools/mailer/new_campaign', mailer_views.new_mailer_campaign, name="new_mailer_campaign"),
    path('tools/mailer', mailer_views.get_mail_campaigns, name="get_mail_campaigns"),
    re_path(r'tools/mailer/campaign_details/(?P<id>\d*)', mailer_views.get_campaign_details, name="get_campaign_details"),
    path('api/tools/mailer/new_campaign_post', mailer_views.new_mailer_campaign_post, name="new_mailer_campaign_post"),
    path('api/tools/mailer/campaign/msg_preview', mailer_views.get_campaign_message_preview, name="get_campaign_message_preview"),
    path('api/tools/mailer/campaign/delete', mailer_views.delete_campaign, name="delete_campaign"),

    path('tools/applications', application_views.get_applications_html, name="get_applications_html"),
    path('tools/applications/new', application_views.new_application, name="new_application"),
    path('api/tools/applications/applicants', application_views.get_applicants, name="get_applicants"),
    path('api/tools/applications/courses', application_views.get_courses, name="get_courses"),
    path('api/tools/applications/status', application_views.get_applications_statuses, name="get_applications_statuses"),
    path('api/tools/applications/save', application_views.save_application_endpoint, name="save_application_endpoint"),
    path('api/tools/applications/delete', application_views.delete_application_endpoint, name="delete_application_endpoint"),
]

teaching_pool_project/web/templates/web/reports/applications_list.html
{% extends "web/base.html" %}
{% load bootstrap4 %}
{% load course_tags %}
{% load mathfilters %}
{% load applications_tags %}
{% block headers %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-html5-1.5.6/fh-3.1.4/sc-2.0.0/datatables.min.css"/>

{% endblock headers %}
{% block maincontent %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Base information</h4>
        <p class="card-text">Year: {{ year }}</p>
        <p class="card-text">Term: {{ term }}</p>
        <div id="ButtonBar"></div>
    </div>
</div>
<table class="table table-striped table-inverse table-responsive" id="applications">
    <thead class="thead-inverse">
        <tr>
            <th class="align-top" rowspan="2">PhD</th>
            <th class="align-top text-center" colspan="3">Course</th>
            <th class="align-top" rowspan="2">Status</th>
            <th rowspan="2"></th>
        </tr>
        <tr>
            <th>Section</th>
            <th>Subject</th>
            <th>Teachers</th>
        </tr>
        </thead>
        <tbody>
            {% for application in applications %}
            <tr>
                <td>{{ application.applicant.last_name }}, {{ application.applicant.first_name }} ({{ application.applicant.sciper }})<a href="{% url "web:view_profile" application.applicant.pk %}" target="_blank"><i style="margin-left: 5px;" class="fas fa-external-link-alt"></i></a></td>
                <td>{% get_application_section application %}</td>
                <td>{{ application.course.subject }} ({{ application.course.code }})</td>
                <td>{% get_application_course_teachers application %}</td>
                <td>{{ application.status }}</td>
                <td><a class="fa fa-trash" href="{% url "web:delete_application" application.id %}"></a></td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot class="thead-inverse">
        <tr>
            <th>name</th>
            <th>section</th>
            <th>course</th>
            <th>teachers</th>
            <th>Status</th>
            <th></th>
        </tr>
        </tfoot>
</table>
{% endblock maincontent %}
{% block scripts%}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-html5-1.5.6/fh-3.1.4/sc-2.0.0/datatables.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
    // Setup - add a text input to each footer cell
    $('#applications tfoot th').each( function () {
        var title = $(this).text();
        if (title != ''){
            $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
        }

    } );

    // DataTable
    var table = $('#applications').DataTable(
        {
            //dom: 'B<"clear">lfrtip',
            dom: 'B<"clear">'+
                "<'row'<'col-sm-6'l><'col-sm-6'f>>" +
                "<'row'<'col-sm-12'tr>>" +
                "<'row'<'col-sm-5'i><'col-sm-7'p>>",
            'columnDefs': [
                {'orderable': false, 'targets': [-1,3]},
                {'searchable': false, 'targets': -1}
            ],
            'order':[[0, 'asc']],
            "scrollX": true,
            buttons: [
                {
                    extend: 'excel',
                    text: '<i class="fa fa-file-excel-o"></i>&nbsp;Download excel file',
                    className: 'btnDummy',
                    exportOptions: {
                        modifier: {
                            order: 'current',
                            search: 'applied',
                            page: 'all'
                            }
                    },
                    extension: '.xlsx',
                    filename: 'applications_' + moment().format('YMMDD_HHmmss'),
                    title: 'List of applications',
                    messageTop: 'applications as of ' + moment().format('DD.MM.Y') + ' at ' + moment().format('HH:mm:ss') + ' - year: {{ year }} - term: {{ term }}'
                }
            ]
        }
    );
    table.buttons().container().insertAfter( '#ButtonBar' );

    // stupid trick to make sure that the button will get displayed as a primary button
    $(".btnDummy").removeClass( "btn-secondary" ).removeClass('btnDummy').addClass( "btn-primary");

    // Apply the search
    table.columns().every( function () {
        var that = this;

        $( 'input', this.footer() ).on( 'keyup change clear', function () {
            if ( that.search() !== this.value ) {
                that
                    .search( this.value )
                    .draw();
            }
        } );
    } );
} );
</script>
{%endblock scripts%}

teaching_pool_project/web/templates/web/reports/courses_list.html
{% extends "web/base.html" %}
{% load bootstrap4 %}
{% load course_tags %}
{% load mathfilters %}
{% load static %}
{% block headers%}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css">
<link rel="stylesheet" href="{% static 'web/css/tables.css' %}">
{% endblock headers %}
{% block maincontent %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Base information</h4>
        <p class="card-text">Year: {{ year }}</p>
        <p class="card-text">Term: {{ term }}</p>
        <div id="ButtonBar"></div>
    </div>
</div>
<div class="card" id="searchCard">
    <div class="card-body">
        <h4 class="card-title">Filters</h4>
        <p class="card-text"></p>
    </div>
</div>
<table class="stripe row-border order-column" style="width:100%" id="courses">
    <thead>
        <tr>
            <th class="text-left align-top" data-search-title="Course subject">Subject</th>
            <th class="text-left align-top" data-search-title="Course teacher(s)">Teachers</th>
            <th class="text-left align-top" data-search-title="Course section(s)">Section(s)</th>
            <th class="text-left align-top" data-search-title="Course form(s)">Form(s)</th>
            <th class="text-left align-top" data-search-title="Course language(s)">Course lang.</th>
            <th class="text-center align-top" data-search-title="# of students (prev. year)"># Students (prev. year)</th>
            <th class="text-center align-top" data-search-title="Theorical # of TAs"># TAs theory</th>
            <th class="text-center align-top" data-search-title="Requested # of TAs"># TAs req.</th>
            <th class="text-center align-top" data-search-title="Approved # of TAs"># TAs appr.</th>
            <th class="text-center align-top" data-search-title="# of received applications"># appl. rec.</th>
            <th class="text-center align-top" data-search-title="# of accepted applications"># appl. acc.</th>
            <th class="text-center align-top" data-search-title="# of declined applications"># appl. decl.</th>
            <th class="text-center align-top" data-search-title="# of withdrawn applications"># appl. with.</th>
            <th class="text-center align-top" data-search-title="# of TA seats to be filled"># seats 2 B filled</th>
        </tr>
    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <td class="text-left align-top">{{ course.subject }} ({{ course.code }})</td>
            <td class="text-left align-top">{{ course|format_teachers }}</td>
            <td class="text-left align-top">{{ course|format_sections:sections|default_if_none:"&nbsp;" }}</td>
            <td class="text-left align-top">{{ course|format_forms }}</td>
            <td class="text-left align-top">{{ course|format_languages }}</td>
            <td class="text-center align-top" >{{ course.numberOfStudents|default_if_none:"&nbsp;" }}</td>
            <td class="text-center align-top" >{{ course.calculatedNumberOfTAs|default_if_none:"&nbsp;" }}</td>
            <td class="text-center align-top" >{{ course.requestedNumberOfTAs|default_if_none:"&nbsp;" }}</td>
            <td class="text-center align-top" >{{ course.approvedNumberOfTAs|default_if_none:"&nbsp;" }}</td>
            <td class="text-center align-top" ><i data-toggle="tooltip" data-year="{{ CURRENT_YEAR }}" data-term="{{ CURRENT_TERM }}" data-course-code="{{ course.code }}" data-application-type="received" data-number="{{ course.applications_received|default_if_none:0 }}">{{ course.applications_received|default_if_none:"&nbsp;" }}</i></td>
            <td class="text-center align-top" ><i data-toggle="tooltip" data-year="{{ CURRENT_YEAR }}" data-term="{{ CURRENT_TERM }}" data-course-code="{{ course.code }}" data-application-type="Hired" data-number="{{ course.applications_received|default_if_none:0 }}">{{ course.applications_accepted|default_if_none:"&nbsp;" }}</i></td>
            <td class="text-center align-top" ><i data-toggle="tooltip" data-year="{{ CURRENT_YEAR }}" data-term="{{ CURRENT_TERM }}" data-course-code="{{ course.code }}" data-application-type="Rejected" data-number="{{ course.applications_received|default_if_none:0 }}">{{ course.applications_rejected|default_if_none:"&nbsp;" }}</i></td>
            <td class="text-center align-top" ><i data-toggle="tooltip" data-year="{{ CURRENT_YEAR }}" data-term="{{ CURRENT_TERM }}" data-course-code="{{ course.code }}" data-application-type="Withdrawn" data-number="{{ course.applications_received|default_if_none:0 }}">{{ course.applications_withdrawn|default_if_none:"&nbsp;" }}</i></td>
            <td class="text-center align-top" >{{ course.approvedNumberOfTAs|sub:course.applications_accepted|default_if_none:"&nbsp;" }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock maincontent %}
{% block scripts%}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.18/b-1.5.6/b-html5-1.5.6/fh-3.1.4/sc-2.0.0/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/3.3.0/js/dataTables.fixedColumns.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script>
// get entry details for tooltip
function getDetails(){
    var number = $(this).data('number');
    if (number == 0) {
        return 'No details available';
    }
    else {
        var year = $(this).data('year');
        var courseCode = $(this).data('courseCode');
        var term = $(this).data('term')
        var type = $(this).data('applicationType');

        var tooltipText = "";

        $.ajax({
            url: '{%url 'web:api_get_course_applications_details'%}',
            type: 'post',
            async: false,
            data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'year': year,
                'term': term,
                'courseCode': courseCode,
                'type': type
                },
            success: function(response){
                 tooltipText=response;
                 },
            error: function(jqXHR, textStatus, errorThrown){
                tooltipText=textStatus + " - " + errorThrown + " (" + jqXHR.status + " - " + jqXHR.statusText + ")";
            }
        });

        return tooltipText;
    }
}

$(document).ready(function(){
    // tooltips
    $('[data-toggle="tooltip"]').tooltip({
        delay: {'show': 500, 'hide': 1500},
        title: getDetails,
        html: true
    });

    // Create the search fields for each column
    $('#courses thead th').each(function(){
        var title = $(this).data('search-title').toLowerCase();
        if (title != '') {
            var searchCardPlaceholder = $('#searchCard').find('.card-text');
            searchCardPlaceholder.append('<div class="input-group input-group-sm mb-3"><div class="input-group-prepend"><span class="input-group-text">' + title + '</span></div><input type="text" data-title="'+title+'" class="form-control" placeholder="Search for ' + title + '"></div>');
        }
    });

    // DataTable
    var table = $('#courses').removeAttr('width').DataTable(
        {
            columnDefs:[
                {responsivePriority: 1, targets: 0},
                {responsivePriority: 9999, targets: [9,10,11,12]},
                {responsivePriority: 10002, targets: [1,3,4]},
                {responsivePriority: 10003, targets: [5,6,7]},
                {responsivePriority: 2, targets: -1},
                {responsivePriority: 3, targets: 8},
                {width: 50, targets: [8,-1]}
            ],
            responsive: true,
            'order':[[0, 'asc']],
            scrollCollapse: true,
            buttons: [
                {
                    extend: 'excel',
                    text: '<i class="fa fa-file-excel-o"></i>&nbsp;Download excel file',
                    className: 'btnDummy',
                    exportOptions: {
                        modifier: {
                            order: 'current',
                            search: 'applied',
                            page: 'all'
                            }
                    },
                    extension: '.xlsx',
                    filename: 'courses_{{ year }}_{{ term }}_' + moment().format('YMMDD_HHmmss'),
                    title: 'List of courses',
                    messageTop: '{{ year }} - {{ term }} courses as of ' + moment().format('DD.MM.Y') + ' at ' + moment().format('HH:mm:ss')
                }
            ]
        }
    );
    table.buttons().container().insertAfter( '#ButtonBar' );

    // stupid trick to make sure that the button will get displayed as a primary button
    $(".btnDummy").removeClass( "btn-secondary" ).removeClass('btnDummy').addClass( "btn-primary");

    // Apply the search
    table.columns().every( function () {
        var that = this;
        var data_search_title = $(this.header()).data('search-title').toLowerCase();

        $('input[data-title*="'+data_search_title+'"]', '#searchCard').on('keyup change clear', function() {
            if (that.search !== this.value){
                that
                    .search(this.value)
                    .draw();
            }
        });
    } );
});
</script>
{%endblock scripts%}

teaching_pool_project/web/templates/web/reports/phds_list.html
{% extends "web/base.html" %}
{% load bootstrap4 %}
{% load course_tags %}
{% load mathfilters %}
{% block headers %}
{% comment %} <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css"> {% endcomment %}
<link rel="stylesheet" type="text/css" href='https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css'>
{% endblock headers %}
{% block maincontent %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Base information</h4>
        <p class="card-text">Year: {{ year }}</p>
        <p class="card-text">Term: {{ term }}</p>
        <a class="btn btn-primary btn-block" href="{% url "web:download_phds_report" year term %}" role="button"><i class="fa fa-file-excel-o"></i>&nbsp;Download Excel file</a>
    </div>
</div>
<table class="table table-sm table-striped table-inverse table-responsive" id="phds">
    <thead class="thead-inverse">
        <tr>
            <th class="align-top text-left" rowspan="2">Name</th>
            <th class="align-top text-center" rowspan="2"><i class="far fa-id-card"></i></th>
            <th class="align-top text-left" rowspan="2">Availability</th>
            <th class="align-top text-center" colspan="4">Applications</th>
        </tr>
        <tr>
            <th class="text-right">pending</th>
            <th class="text-right">accepted</th>
            <th class="text-right">declined</th>
            <th class="text-right">withdrawn</th>
        </tr>
        </thead>
        <tbody>
            {% for phd in phds %}
            <tr>
                <td class="text-left">{{ phd.last_name }}, {{ phd.first_name }}</td>
                <td class="text-center"><a href='{% url "web:view_profile" phd.id%}' target="_blank"><i class="fas fa-external-link-alt"></i></a></td>
                <td class="text-left">{{ phd.availability }}</td>
                <td class="text-right">{{ phd.applications_pending }}</td>
                <td class="text-right">{{ phd.applications_accepted }}</td>
                <td class="text-right">{{ phd.applications_declined }}</td>
                <td class="text-right">{{ phd.applications_withdrawn }}</td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot class="thead-inverse">
        <tr>
            <th>Name</th>
            <th></th>
            <th>Avail.</th>
            <th>Pending appl.</th>
            <th>Acepted appl.</th>
            <th>Declined appl.</th>
            <th>Withdrawn appl.</th>
        </tr>
        </tfoot>
</table>
{% endblock maincontent %}
{% block scripts%}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    // Setup - add a text input to each footer cell
    $('#phds tfoot th').each( function () {
        var title = $(this).text();
        if (title != ''){
            $(this).html( '<input type="text" placeholder="Search '+title.toLowerCase()+'" />' );
        }
    } );

    // DataTable
    var table = $('#phds').DataTable(
        {
            'order':[[0, 'asc']],
            'columnDefs': [
                {
                    'targets': 1,
                    'orderable': false
                },
            ],
            "scrollX": true,
        }
    );

    // Apply the search
    table.columns().every( function () {
        var that = this;

        $( 'input', this.footer() ).on( 'keyup change clear', function () {
            if ( that.search() !== this.value ) {
                that
                    .search( this.value )
                    .draw();
            }
        } );
    } );
} );
</script>
{%endblock scripts%}

teaching_pool_project/web/templates/web/reports/phds_with_multiple_hirings.html
{% extends "web/base.html" %}
{% load bootstrap4 %}
{% load applications_tags %}

{% block maincontent %}
<div class="row">
    <div class="col">
        <h2>List of PhDs being accepted in multiple courses</h2>
        <div class="card-columns">
        {% regroup hirings|dictsort:"closedAt" by applicant as applicants_by_course %}
        {% for applicant in applicants_by_course %}
            {% if applicant.list|length > 1 %}
                <div class="card">
                    <div class="card-header">
                        <i class="fa fa-graduation-cap" aria-hidden="true"></i>&nbsp;{{ applicant.grouper.last_name }}, {{ applicant.grouper.first_name }}
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for application in applicant.list %}
                        <li class="list-group-item">{{ application.course.subject }} ({{ application.course.code }})<p><small>application accepted on {{ application.closedAt|date:'d b Y' }}</small></p></li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endfor %}
        </div>
        <p><small>If you don't see anything between the header and this line, it means that no PhD is currently hired twice.</small></p>
    </div>
</div>

{% endblock maincontent %}
{% block scripts%}
{%endblock scripts%}